
// Copyright 2024 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by
//     java_cpp_enum.py
// From
//     ../../chrome/browser/vr/ui_test_input.h

package org.chromium.chrome.browser.vr_shell;

import androidx.annotation.IntDef;

import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;

@IntDef({
    VrUiTestAction.HOVER_ENTER, VrUiTestAction.HOVER_LEAVE, VrUiTestAction.MOVE,
    VrUiTestAction.BUTTON_DOWN, VrUiTestAction.BUTTON_UP
})
@Retention(RetentionPolicy.SOURCE)
public @interface VrUiTestAction {
  int HOVER_ENTER = 0;
  int HOVER_LEAVE = 1;
  int MOVE = 2;
  int BUTTON_DOWN = 3;
  int BUTTON_UP = 4;
}
