// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/search/now/proto/ui/stream/stream_structure.proto

package com.google.search.now.ui.stream;

public final class StreamStructureProto {
  private StreamStructureProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
    registry.add(com.google.search.now.ui.stream.StreamStructureProto.Stream.streamExtension);
    registry.add(com.google.search.now.ui.stream.StreamStructureProto.Cluster.clusterExtension);
    registry.add(com.google.search.now.ui.stream.StreamStructureProto.Card.cardExtension);
    registry.add(com.google.search.now.ui.stream.StreamStructureProto.Content.contentExtension);
    registry.add(com.google.search.now.ui.stream.StreamStructureProto.PietContent.pietContentExtension);
  }
  public interface StreamOrBuilder extends
      // @@protoc_insertion_point(interface_extends:search.now.ui.stream.Stream)
      com.google.protobuf.MessageLiteOrBuilder {
  }
  /**
   * <pre>
   * Top level feature which shows a stream of cards.  Provides any UI inforamtion
   * which may be needed in order to render the stream of cards.
   * </pre>
   *
   * Protobuf type {@code search.now.ui.stream.Stream}
   */
  public  static final class Stream extends
      com.google.protobuf.GeneratedMessageLite<
          Stream, Stream.Builder> implements
      // @@protoc_insertion_point(message_implements:search.now.ui.stream.Stream)
      StreamOrBuilder {
    private Stream() {
    }
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      size += unknownFields.getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    public static com.google.search.now.ui.stream.StreamStructureProto.Stream parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.google.search.now.ui.stream.StreamStructureProto.Stream parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.google.search.now.ui.stream.StreamStructureProto.Stream parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.google.search.now.ui.stream.StreamStructureProto.Stream parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.google.search.now.ui.stream.StreamStructureProto.Stream parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.google.search.now.ui.stream.StreamStructureProto.Stream parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.google.search.now.ui.stream.StreamStructureProto.Stream parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.google.search.now.ui.stream.StreamStructureProto.Stream parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.google.search.now.ui.stream.StreamStructureProto.Stream parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.google.search.now.ui.stream.StreamStructureProto.Stream parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.google.search.now.ui.stream.StreamStructureProto.Stream parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.google.search.now.ui.stream.StreamStructureProto.Stream parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.google.search.now.ui.stream.StreamStructureProto.Stream prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * <pre>
     * Top level feature which shows a stream of cards.  Provides any UI inforamtion
     * which may be needed in order to render the stream of cards.
     * </pre>
     *
     * Protobuf type {@code search.now.ui.stream.Stream}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.google.search.now.ui.stream.StreamStructureProto.Stream, Builder> implements
        // @@protoc_insertion_point(builder_implements:search.now.ui.stream.Stream)
        com.google.search.now.ui.stream.StreamStructureProto.StreamOrBuilder {
      // Construct using com.google.search.now.ui.stream.StreamStructureProto.Stream.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      // @@protoc_insertion_point(builder_scope:search.now.ui.stream.Stream)
    }
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.google.search.now.ui.stream.StreamStructureProto.Stream();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          com.google.search.now.ui.stream.StreamStructureProto.Stream other = (com.google.search.now.ui.stream.StreamStructureProto.Stream) arg1;
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!parseUnknownField(tag, input)) {
                    done = true;
                  }
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (com.google.search.now.ui.stream.StreamStructureProto.Stream.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:search.now.ui.stream.Stream)
    private static final com.google.search.now.ui.stream.StreamStructureProto.Stream DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Stream();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static com.google.search.now.ui.stream.StreamStructureProto.Stream getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<Stream> PARSER;

    public static com.google.protobuf.Parser<Stream> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
    public static final int STREAM_EXTENSION_FIELD_NUMBER = 185431437;
    /**
     * <code>extend .search.now.proto.wire.feed.Feature { ... }</code>
     */
    public static final
      com.google.protobuf.GeneratedMessageLite.GeneratedExtension<
        com.google.search.now.wire.feed.FeatureProto.Feature,
        com.google.search.now.ui.stream.StreamStructureProto.Stream> streamExtension = com.google.protobuf.GeneratedMessageLite
            .newSingularGeneratedExtension(
          com.google.search.now.wire.feed.FeatureProto.Feature.getDefaultInstance(),
          com.google.search.now.ui.stream.StreamStructureProto.Stream.getDefaultInstance(),
          com.google.search.now.ui.stream.StreamStructureProto.Stream.getDefaultInstance(),
          null,
          185431437,
          com.google.protobuf.WireFormat.FieldType.MESSAGE,
          com.google.search.now.ui.stream.StreamStructureProto.Stream.class);
  }

  public interface ClusterOrBuilder extends
      // @@protoc_insertion_point(interface_extends:search.now.ui.stream.Cluster)
      com.google.protobuf.MessageLiteOrBuilder {
  }
  /**
   * <pre>
   * Feature which represents a cluster in a Stream. May have a Card or Content
   * as children.
   * </pre>
   *
   * Protobuf type {@code search.now.ui.stream.Cluster}
   */
  public  static final class Cluster extends
      com.google.protobuf.GeneratedMessageLite<
          Cluster, Cluster.Builder> implements
      // @@protoc_insertion_point(message_implements:search.now.ui.stream.Cluster)
      ClusterOrBuilder {
    private Cluster() {
    }
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      size += unknownFields.getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    public static com.google.search.now.ui.stream.StreamStructureProto.Cluster parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.google.search.now.ui.stream.StreamStructureProto.Cluster parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.google.search.now.ui.stream.StreamStructureProto.Cluster parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.google.search.now.ui.stream.StreamStructureProto.Cluster parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.google.search.now.ui.stream.StreamStructureProto.Cluster parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.google.search.now.ui.stream.StreamStructureProto.Cluster parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.google.search.now.ui.stream.StreamStructureProto.Cluster parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.google.search.now.ui.stream.StreamStructureProto.Cluster parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.google.search.now.ui.stream.StreamStructureProto.Cluster parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.google.search.now.ui.stream.StreamStructureProto.Cluster parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.google.search.now.ui.stream.StreamStructureProto.Cluster parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.google.search.now.ui.stream.StreamStructureProto.Cluster parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.google.search.now.ui.stream.StreamStructureProto.Cluster prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * <pre>
     * Feature which represents a cluster in a Stream. May have a Card or Content
     * as children.
     * </pre>
     *
     * Protobuf type {@code search.now.ui.stream.Cluster}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.google.search.now.ui.stream.StreamStructureProto.Cluster, Builder> implements
        // @@protoc_insertion_point(builder_implements:search.now.ui.stream.Cluster)
        com.google.search.now.ui.stream.StreamStructureProto.ClusterOrBuilder {
      // Construct using com.google.search.now.ui.stream.StreamStructureProto.Cluster.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      // @@protoc_insertion_point(builder_scope:search.now.ui.stream.Cluster)
    }
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.google.search.now.ui.stream.StreamStructureProto.Cluster();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          com.google.search.now.ui.stream.StreamStructureProto.Cluster other = (com.google.search.now.ui.stream.StreamStructureProto.Cluster) arg1;
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!parseUnknownField(tag, input)) {
                    done = true;
                  }
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (com.google.search.now.ui.stream.StreamStructureProto.Cluster.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:search.now.ui.stream.Cluster)
    private static final com.google.search.now.ui.stream.StreamStructureProto.Cluster DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Cluster();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static com.google.search.now.ui.stream.StreamStructureProto.Cluster getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<Cluster> PARSER;

    public static com.google.protobuf.Parser<Cluster> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
    public static final int CLUSTER_EXTENSION_FIELD_NUMBER = 190812910;
    /**
     * <code>extend .search.now.proto.wire.feed.Feature { ... }</code>
     */
    public static final
      com.google.protobuf.GeneratedMessageLite.GeneratedExtension<
        com.google.search.now.wire.feed.FeatureProto.Feature,
        com.google.search.now.ui.stream.StreamStructureProto.Cluster> clusterExtension = com.google.protobuf.GeneratedMessageLite
            .newSingularGeneratedExtension(
          com.google.search.now.wire.feed.FeatureProto.Feature.getDefaultInstance(),
          com.google.search.now.ui.stream.StreamStructureProto.Cluster.getDefaultInstance(),
          com.google.search.now.ui.stream.StreamStructureProto.Cluster.getDefaultInstance(),
          null,
          190812910,
          com.google.protobuf.WireFormat.FieldType.MESSAGE,
          com.google.search.now.ui.stream.StreamStructureProto.Cluster.class);
  }

  public interface CardOrBuilder extends 
      // @@protoc_insertion_point(interface_extends:search.now.ui.stream.Card)
       com.google.protobuf.GeneratedMessageLite.
            ExtendableMessageOrBuilder<
                Card, Card.Builder> {
  }
  /**
   * <pre>
   * Feature which represents a full card in a Stream.  Allows metadata to be sent
   * to describe how to render the card.
   * </pre>
   *
   * Protobuf type {@code search.now.ui.stream.Card}
   */
  public  static final class Card extends
      com.google.protobuf.GeneratedMessageLite.ExtendableMessage<
        Card, Card.Builder> implements
      // @@protoc_insertion_point(message_implements:search.now.ui.stream.Card)
      CardOrBuilder {
    private Card() {
    }
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      com.google.protobuf.GeneratedMessageLite
        .ExtendableMessage<com.google.search.now.ui.stream.StreamStructureProto.Card, com.google.search.now.ui.stream.StreamStructureProto.Card.Builder>
          .ExtensionWriter extensionWriter =
            newExtensionWriter();
      extensionWriter.writeUntil(536870912, output);
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      size += extensionsSerializedSize();
      size += unknownFields.getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    public static com.google.search.now.ui.stream.StreamStructureProto.Card parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.google.search.now.ui.stream.StreamStructureProto.Card parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.google.search.now.ui.stream.StreamStructureProto.Card parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.google.search.now.ui.stream.StreamStructureProto.Card parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.google.search.now.ui.stream.StreamStructureProto.Card parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.google.search.now.ui.stream.StreamStructureProto.Card parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.google.search.now.ui.stream.StreamStructureProto.Card parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.google.search.now.ui.stream.StreamStructureProto.Card parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.google.search.now.ui.stream.StreamStructureProto.Card parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.google.search.now.ui.stream.StreamStructureProto.Card parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.google.search.now.ui.stream.StreamStructureProto.Card parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.google.search.now.ui.stream.StreamStructureProto.Card parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.google.search.now.ui.stream.StreamStructureProto.Card prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * <pre>
     * Feature which represents a full card in a Stream.  Allows metadata to be sent
     * to describe how to render the card.
     * </pre>
     *
     * Protobuf type {@code search.now.ui.stream.Card}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.ExtendableBuilder<
          com.google.search.now.ui.stream.StreamStructureProto.Card, Builder> implements
        // @@protoc_insertion_point(builder_implements:search.now.ui.stream.Card)
        com.google.search.now.ui.stream.StreamStructureProto.CardOrBuilder {
      // Construct using com.google.search.now.ui.stream.StreamStructureProto.Card.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      // @@protoc_insertion_point(builder_scope:search.now.ui.stream.Card)
    }
    private byte memoizedIsInitialized = -1;
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.google.search.now.ui.stream.StreamStructureProto.Card();
        }
        case IS_INITIALIZED: {
          byte isInitialized = memoizedIsInitialized;
          if (isInitialized == 1) return DEFAULT_INSTANCE;
          if (isInitialized == 0) return null;

          boolean shouldMemoize = ((Boolean) arg0).booleanValue();
          if (!extensionsAreInitialized()) {
            if (shouldMemoize) {
              memoizedIsInitialized = 0;
            }
            return null;
          }
          if (shouldMemoize) memoizedIsInitialized = 1;
          return DEFAULT_INSTANCE;

        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          com.google.search.now.ui.stream.StreamStructureProto.Card other = (com.google.search.now.ui.stream.StreamStructureProto.Card) arg1;
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!parseUnknownField(getDefaultInstanceForType(),
                      input, extensionRegistry, tag)) {
                    done = true;
                  }
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (com.google.search.now.ui.stream.StreamStructureProto.Card.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:search.now.ui.stream.Card)
    private static final com.google.search.now.ui.stream.StreamStructureProto.Card DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Card();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static com.google.search.now.ui.stream.StreamStructureProto.Card getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<Card> PARSER;

    public static com.google.protobuf.Parser<Card> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
    public static final int CARD_EXTENSION_FIELD_NUMBER = 185431438;
    /**
     * <code>extend .search.now.proto.wire.feed.Feature { ... }</code>
     */
    public static final
      com.google.protobuf.GeneratedMessageLite.GeneratedExtension<
        com.google.search.now.wire.feed.FeatureProto.Feature,
        com.google.search.now.ui.stream.StreamStructureProto.Card> cardExtension = com.google.protobuf.GeneratedMessageLite
            .newSingularGeneratedExtension(
          com.google.search.now.wire.feed.FeatureProto.Feature.getDefaultInstance(),
          com.google.search.now.ui.stream.StreamStructureProto.Card.getDefaultInstance(),
          com.google.search.now.ui.stream.StreamStructureProto.Card.getDefaultInstance(),
          null,
          185431438,
          com.google.protobuf.WireFormat.FieldType.MESSAGE,
          com.google.search.now.ui.stream.StreamStructureProto.Card.class);
  }

  public interface ContentOrBuilder extends 
      // @@protoc_insertion_point(interface_extends:search.now.ui.stream.Content)
       com.google.protobuf.GeneratedMessageLite.
            ExtendableMessageOrBuilder<
                Content, Content.Builder> {

    /**
     * <code>optional .search.now.ui.stream.Content.Type type = 1;</code>
     */
    boolean hasType();
    /**
     * <code>optional .search.now.ui.stream.Content.Type type = 1;</code>
     */
    com.google.search.now.ui.stream.StreamStructureProto.Content.Type getType();
  }
  /**
   * <pre>
   * Feature which is able to show actual content in a stream. This could be
   * inside or outside a card. Actual data on what to display will be sent on an
   * extension.
   * </pre>
   *
   * Protobuf type {@code search.now.ui.stream.Content}
   */
  public  static final class Content extends
      com.google.protobuf.GeneratedMessageLite.ExtendableMessage<
        Content, Content.Builder> implements
      // @@protoc_insertion_point(message_implements:search.now.ui.stream.Content)
      ContentOrBuilder {
    private Content() {
    }
    /**
     * Protobuf enum {@code search.now.ui.stream.Content.Type}
     */
    public enum Type
        implements com.google.protobuf.Internal.EnumLite {
      /**
       * <code>UNKNOWN_CONTENT = 0;</code>
       */
      UNKNOWN_CONTENT(0),
      /**
       * <code>PIET = 1;</code>
       */
      PIET(1),
      ;

      /**
       * <code>UNKNOWN_CONTENT = 0;</code>
       */
      public static final int UNKNOWN_CONTENT_VALUE = 0;
      /**
       * <code>PIET = 1;</code>
       */
      public static final int PIET_VALUE = 1;


      public final int getNumber() {
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Type valueOf(int value) {
        return forNumber(value);
      }

      public static Type forNumber(int value) {
        switch (value) {
          case 0: return UNKNOWN_CONTENT;
          case 1: return PIET;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Type> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Type>() {
              public Type findValueByNumber(int number) {
                return Type.forNumber(number);
              }
            };

      private final int value;

      private Type(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:search.now.ui.stream.Content.Type)
    }

    private int bitField0_;
    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <code>optional .search.now.ui.stream.Content.Type type = 1;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .search.now.ui.stream.Content.Type type = 1;</code>
     */
    public com.google.search.now.ui.stream.StreamStructureProto.Content.Type getType() {
      com.google.search.now.ui.stream.StreamStructureProto.Content.Type result = com.google.search.now.ui.stream.StreamStructureProto.Content.Type.forNumber(type_);
      return result == null ? com.google.search.now.ui.stream.StreamStructureProto.Content.Type.UNKNOWN_CONTENT : result;
    }
    /**
     * <code>optional .search.now.ui.stream.Content.Type type = 1;</code>
     */
    private void setType(com.google.search.now.ui.stream.StreamStructureProto.Content.Type value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000001;
      type_ = value.getNumber();
    }
    /**
     * <code>optional .search.now.ui.stream.Content.Type type = 1;</code>
     */
    private void clearType() {
      bitField0_ = (bitField0_ & ~0x00000001);
      type_ = 0;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      com.google.protobuf.GeneratedMessageLite
        .ExtendableMessage<com.google.search.now.ui.stream.StreamStructureProto.Content, com.google.search.now.ui.stream.StreamStructureProto.Content.Builder>
          .ExtensionWriter extensionWriter =
            newExtensionWriter();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, type_);
      }
      extensionWriter.writeUntil(536870912, output);
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_);
      }
      size += extensionsSerializedSize();
      size += unknownFields.getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    public static com.google.search.now.ui.stream.StreamStructureProto.Content parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.google.search.now.ui.stream.StreamStructureProto.Content parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.google.search.now.ui.stream.StreamStructureProto.Content parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.google.search.now.ui.stream.StreamStructureProto.Content parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.google.search.now.ui.stream.StreamStructureProto.Content parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.google.search.now.ui.stream.StreamStructureProto.Content parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.google.search.now.ui.stream.StreamStructureProto.Content parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.google.search.now.ui.stream.StreamStructureProto.Content parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.google.search.now.ui.stream.StreamStructureProto.Content parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.google.search.now.ui.stream.StreamStructureProto.Content parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.google.search.now.ui.stream.StreamStructureProto.Content parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.google.search.now.ui.stream.StreamStructureProto.Content parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.google.search.now.ui.stream.StreamStructureProto.Content prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * <pre>
     * Feature which is able to show actual content in a stream. This could be
     * inside or outside a card. Actual data on what to display will be sent on an
     * extension.
     * </pre>
     *
     * Protobuf type {@code search.now.ui.stream.Content}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.ExtendableBuilder<
          com.google.search.now.ui.stream.StreamStructureProto.Content, Builder> implements
        // @@protoc_insertion_point(builder_implements:search.now.ui.stream.Content)
        com.google.search.now.ui.stream.StreamStructureProto.ContentOrBuilder {
      // Construct using com.google.search.now.ui.stream.StreamStructureProto.Content.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>optional .search.now.ui.stream.Content.Type type = 1;</code>
       */
      public boolean hasType() {
        return instance.hasType();
      }
      /**
       * <code>optional .search.now.ui.stream.Content.Type type = 1;</code>
       */
      public com.google.search.now.ui.stream.StreamStructureProto.Content.Type getType() {
        return instance.getType();
      }
      /**
       * <code>optional .search.now.ui.stream.Content.Type type = 1;</code>
       */
      public Builder setType(com.google.search.now.ui.stream.StreamStructureProto.Content.Type value) {
        copyOnWrite();
        instance.setType(value);
        return this;
      }
      /**
       * <code>optional .search.now.ui.stream.Content.Type type = 1;</code>
       */
      public Builder clearType() {
        copyOnWrite();
        instance.clearType();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:search.now.ui.stream.Content)
    }
    private byte memoizedIsInitialized = -1;
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.google.search.now.ui.stream.StreamStructureProto.Content();
        }
        case IS_INITIALIZED: {
          byte isInitialized = memoizedIsInitialized;
          if (isInitialized == 1) return DEFAULT_INSTANCE;
          if (isInitialized == 0) return null;

          boolean shouldMemoize = ((Boolean) arg0).booleanValue();
          if (!extensionsAreInitialized()) {
            if (shouldMemoize) {
              memoizedIsInitialized = 0;
            }
            return null;
          }
          if (shouldMemoize) memoizedIsInitialized = 1;
          return DEFAULT_INSTANCE;

        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          com.google.search.now.ui.stream.StreamStructureProto.Content other = (com.google.search.now.ui.stream.StreamStructureProto.Content) arg1;
          type_ = visitor.visitInt(hasType(), type_,
              other.hasType(), other.type_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
            bitField0_ |= other.bitField0_;
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!parseUnknownField(getDefaultInstanceForType(),
                      input, extensionRegistry, tag)) {
                    done = true;
                  }
                  break;
                }
                case 8: {
                  int rawValue = input.readEnum();
                  com.google.search.now.ui.stream.StreamStructureProto.Content.Type value = com.google.search.now.ui.stream.StreamStructureProto.Content.Type.forNumber(rawValue);
                  if (value == null) {
                    super.mergeVarintField(1, rawValue);
                  } else {
                    bitField0_ |= 0x00000001;
                    type_ = rawValue;
                  }
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (com.google.search.now.ui.stream.StreamStructureProto.Content.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:search.now.ui.stream.Content)
    private static final com.google.search.now.ui.stream.StreamStructureProto.Content DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Content();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static com.google.search.now.ui.stream.StreamStructureProto.Content getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<Content> PARSER;

    public static com.google.protobuf.Parser<Content> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
    public static final int CONTENT_EXTENSION_FIELD_NUMBER = 185431439;
    /**
     * <code>extend .search.now.proto.wire.feed.Feature { ... }</code>
     */
    public static final
      com.google.protobuf.GeneratedMessageLite.GeneratedExtension<
        com.google.search.now.wire.feed.FeatureProto.Feature,
        com.google.search.now.ui.stream.StreamStructureProto.Content> contentExtension = com.google.protobuf.GeneratedMessageLite
            .newSingularGeneratedExtension(
          com.google.search.now.wire.feed.FeatureProto.Feature.getDefaultInstance(),
          com.google.search.now.ui.stream.StreamStructureProto.Content.getDefaultInstance(),
          com.google.search.now.ui.stream.StreamStructureProto.Content.getDefaultInstance(),
          null,
          185431439,
          com.google.protobuf.WireFormat.FieldType.MESSAGE,
          com.google.search.now.ui.stream.StreamStructureProto.Content.class);
  }

  public interface PietContentOrBuilder extends
      // @@protoc_insertion_point(interface_extends:search.now.ui.stream.PietContent)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <pre>
     * Content Ids of Piet Shared States which should be provided to Piet in order
     * to show its content.
     * </pre>
     *
     * <code>repeated .search.now.proto.wire.feed.ContentId piet_shared_states = 1;</code>
     */
    java.util.List<com.google.search.now.wire.feed.ContentIdProto.ContentId> 
        getPietSharedStatesList();
    /**
     * <pre>
     * Content Ids of Piet Shared States which should be provided to Piet in order
     * to show its content.
     * </pre>
     *
     * <code>repeated .search.now.proto.wire.feed.ContentId piet_shared_states = 1;</code>
     */
    com.google.search.now.wire.feed.ContentIdProto.ContentId getPietSharedStates(int index);
    /**
     * <pre>
     * Content Ids of Piet Shared States which should be provided to Piet in order
     * to show its content.
     * </pre>
     *
     * <code>repeated .search.now.proto.wire.feed.ContentId piet_shared_states = 1;</code>
     */
    int getPietSharedStatesCount();

    /**
     * <pre>
     * The Piet frame to render.
     * </pre>
     *
     * <code>optional .search.now.ui.piet.Frame frame = 2;</code>
     */
    boolean hasFrame();
    /**
     * <pre>
     * The Piet frame to render.
     * </pre>
     *
     * <code>optional .search.now.ui.piet.Frame frame = 2;</code>
     */
    com.google.search.now.ui.piet.PietProto.Frame getFrame();
  }
  /**
   * <pre>
   * Content which is able to show a Piet frame. This includes any data which may
   * be needed to show a Piet frame.
   * </pre>
   *
   * Protobuf type {@code search.now.ui.stream.PietContent}
   */
  public  static final class PietContent extends
      com.google.protobuf.GeneratedMessageLite<
          PietContent, PietContent.Builder> implements
      // @@protoc_insertion_point(message_implements:search.now.ui.stream.PietContent)
      PietContentOrBuilder {
    private PietContent() {
      pietSharedStates_ = emptyProtobufList();
    }
    private int bitField0_;
    public static final int PIET_SHARED_STATES_FIELD_NUMBER = 1;
    private com.google.protobuf.Internal.ProtobufList<com.google.search.now.wire.feed.ContentIdProto.ContentId> pietSharedStates_;
    /**
     * <pre>
     * Content Ids of Piet Shared States which should be provided to Piet in order
     * to show its content.
     * </pre>
     *
     * <code>repeated .search.now.proto.wire.feed.ContentId piet_shared_states = 1;</code>
     */
    public java.util.List<com.google.search.now.wire.feed.ContentIdProto.ContentId> getPietSharedStatesList() {
      return pietSharedStates_;
    }
    /**
     * <pre>
     * Content Ids of Piet Shared States which should be provided to Piet in order
     * to show its content.
     * </pre>
     *
     * <code>repeated .search.now.proto.wire.feed.ContentId piet_shared_states = 1;</code>
     */
    public java.util.List<? extends com.google.search.now.wire.feed.ContentIdProto.ContentIdOrBuilder> 
        getPietSharedStatesOrBuilderList() {
      return pietSharedStates_;
    }
    /**
     * <pre>
     * Content Ids of Piet Shared States which should be provided to Piet in order
     * to show its content.
     * </pre>
     *
     * <code>repeated .search.now.proto.wire.feed.ContentId piet_shared_states = 1;</code>
     */
    public int getPietSharedStatesCount() {
      return pietSharedStates_.size();
    }
    /**
     * <pre>
     * Content Ids of Piet Shared States which should be provided to Piet in order
     * to show its content.
     * </pre>
     *
     * <code>repeated .search.now.proto.wire.feed.ContentId piet_shared_states = 1;</code>
     */
    public com.google.search.now.wire.feed.ContentIdProto.ContentId getPietSharedStates(int index) {
      return pietSharedStates_.get(index);
    }
    /**
     * <pre>
     * Content Ids of Piet Shared States which should be provided to Piet in order
     * to show its content.
     * </pre>
     *
     * <code>repeated .search.now.proto.wire.feed.ContentId piet_shared_states = 1;</code>
     */
    public com.google.search.now.wire.feed.ContentIdProto.ContentIdOrBuilder getPietSharedStatesOrBuilder(
        int index) {
      return pietSharedStates_.get(index);
    }
    private void ensurePietSharedStatesIsMutable() {
      if (!pietSharedStates_.isModifiable()) {
        pietSharedStates_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(pietSharedStates_);
       }
    }

    /**
     * <pre>
     * Content Ids of Piet Shared States which should be provided to Piet in order
     * to show its content.
     * </pre>
     *
     * <code>repeated .search.now.proto.wire.feed.ContentId piet_shared_states = 1;</code>
     */
    private void setPietSharedStates(
        int index, com.google.search.now.wire.feed.ContentIdProto.ContentId value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensurePietSharedStatesIsMutable();
      pietSharedStates_.set(index, value);
    }
    /**
     * <pre>
     * Content Ids of Piet Shared States which should be provided to Piet in order
     * to show its content.
     * </pre>
     *
     * <code>repeated .search.now.proto.wire.feed.ContentId piet_shared_states = 1;</code>
     */
    private void setPietSharedStates(
        int index, com.google.search.now.wire.feed.ContentIdProto.ContentId.Builder builderForValue) {
      ensurePietSharedStatesIsMutable();
      pietSharedStates_.set(index, builderForValue.build());
    }
    /**
     * <pre>
     * Content Ids of Piet Shared States which should be provided to Piet in order
     * to show its content.
     * </pre>
     *
     * <code>repeated .search.now.proto.wire.feed.ContentId piet_shared_states = 1;</code>
     */
    private void addPietSharedStates(com.google.search.now.wire.feed.ContentIdProto.ContentId value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensurePietSharedStatesIsMutable();
      pietSharedStates_.add(value);
    }
    /**
     * <pre>
     * Content Ids of Piet Shared States which should be provided to Piet in order
     * to show its content.
     * </pre>
     *
     * <code>repeated .search.now.proto.wire.feed.ContentId piet_shared_states = 1;</code>
     */
    private void addPietSharedStates(
        int index, com.google.search.now.wire.feed.ContentIdProto.ContentId value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensurePietSharedStatesIsMutable();
      pietSharedStates_.add(index, value);
    }
    /**
     * <pre>
     * Content Ids of Piet Shared States which should be provided to Piet in order
     * to show its content.
     * </pre>
     *
     * <code>repeated .search.now.proto.wire.feed.ContentId piet_shared_states = 1;</code>
     */
    private void addPietSharedStates(
        com.google.search.now.wire.feed.ContentIdProto.ContentId.Builder builderForValue) {
      ensurePietSharedStatesIsMutable();
      pietSharedStates_.add(builderForValue.build());
    }
    /**
     * <pre>
     * Content Ids of Piet Shared States which should be provided to Piet in order
     * to show its content.
     * </pre>
     *
     * <code>repeated .search.now.proto.wire.feed.ContentId piet_shared_states = 1;</code>
     */
    private void addPietSharedStates(
        int index, com.google.search.now.wire.feed.ContentIdProto.ContentId.Builder builderForValue) {
      ensurePietSharedStatesIsMutable();
      pietSharedStates_.add(index, builderForValue.build());
    }
    /**
     * <pre>
     * Content Ids of Piet Shared States which should be provided to Piet in order
     * to show its content.
     * </pre>
     *
     * <code>repeated .search.now.proto.wire.feed.ContentId piet_shared_states = 1;</code>
     */
    private void addAllPietSharedStates(
        java.lang.Iterable<? extends com.google.search.now.wire.feed.ContentIdProto.ContentId> values) {
      ensurePietSharedStatesIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, pietSharedStates_);
    }
    /**
     * <pre>
     * Content Ids of Piet Shared States which should be provided to Piet in order
     * to show its content.
     * </pre>
     *
     * <code>repeated .search.now.proto.wire.feed.ContentId piet_shared_states = 1;</code>
     */
    private void clearPietSharedStates() {
      pietSharedStates_ = emptyProtobufList();
    }
    /**
     * <pre>
     * Content Ids of Piet Shared States which should be provided to Piet in order
     * to show its content.
     * </pre>
     *
     * <code>repeated .search.now.proto.wire.feed.ContentId piet_shared_states = 1;</code>
     */
    private void removePietSharedStates(int index) {
      ensurePietSharedStatesIsMutable();
      pietSharedStates_.remove(index);
    }

    public static final int FRAME_FIELD_NUMBER = 2;
    private com.google.search.now.ui.piet.PietProto.Frame frame_;
    /**
     * <pre>
     * The Piet frame to render.
     * </pre>
     *
     * <code>optional .search.now.ui.piet.Frame frame = 2;</code>
     */
    public boolean hasFrame() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <pre>
     * The Piet frame to render.
     * </pre>
     *
     * <code>optional .search.now.ui.piet.Frame frame = 2;</code>
     */
    public com.google.search.now.ui.piet.PietProto.Frame getFrame() {
      return frame_ == null ? com.google.search.now.ui.piet.PietProto.Frame.getDefaultInstance() : frame_;
    }
    /**
     * <pre>
     * The Piet frame to render.
     * </pre>
     *
     * <code>optional .search.now.ui.piet.Frame frame = 2;</code>
     */
    private void setFrame(com.google.search.now.ui.piet.PietProto.Frame value) {
      if (value == null) {
        throw new NullPointerException();
      }
      frame_ = value;
      bitField0_ |= 0x00000001;
      }
    /**
     * <pre>
     * The Piet frame to render.
     * </pre>
     *
     * <code>optional .search.now.ui.piet.Frame frame = 2;</code>
     */
    private void setFrame(
        com.google.search.now.ui.piet.PietProto.Frame.Builder builderForValue) {
      frame_ = builderForValue.build();
      bitField0_ |= 0x00000001;
    }
    /**
     * <pre>
     * The Piet frame to render.
     * </pre>
     *
     * <code>optional .search.now.ui.piet.Frame frame = 2;</code>
     */
    private void mergeFrame(com.google.search.now.ui.piet.PietProto.Frame value) {
      if (frame_ != null &&
          frame_ != com.google.search.now.ui.piet.PietProto.Frame.getDefaultInstance()) {
        frame_ =
          com.google.search.now.ui.piet.PietProto.Frame.newBuilder(frame_).mergeFrom(value).buildPartial();
      } else {
        frame_ = value;
      }
      bitField0_ |= 0x00000001;
    }
    /**
     * <pre>
     * The Piet frame to render.
     * </pre>
     *
     * <code>optional .search.now.ui.piet.Frame frame = 2;</code>
     */
    private void clearFrame() {  frame_ = null;
      bitField0_ = (bitField0_ & ~0x00000001);
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < pietSharedStates_.size(); i++) {
        output.writeMessage(1, pietSharedStates_.get(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(2, getFrame());
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < pietSharedStates_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, pietSharedStates_.get(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getFrame());
      }
      size += unknownFields.getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    public static com.google.search.now.ui.stream.StreamStructureProto.PietContent parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.google.search.now.ui.stream.StreamStructureProto.PietContent parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.google.search.now.ui.stream.StreamStructureProto.PietContent parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.google.search.now.ui.stream.StreamStructureProto.PietContent parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.google.search.now.ui.stream.StreamStructureProto.PietContent parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.google.search.now.ui.stream.StreamStructureProto.PietContent parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.google.search.now.ui.stream.StreamStructureProto.PietContent parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.google.search.now.ui.stream.StreamStructureProto.PietContent parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.google.search.now.ui.stream.StreamStructureProto.PietContent parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.google.search.now.ui.stream.StreamStructureProto.PietContent parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.google.search.now.ui.stream.StreamStructureProto.PietContent parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.google.search.now.ui.stream.StreamStructureProto.PietContent parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.google.search.now.ui.stream.StreamStructureProto.PietContent prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * <pre>
     * Content which is able to show a Piet frame. This includes any data which may
     * be needed to show a Piet frame.
     * </pre>
     *
     * Protobuf type {@code search.now.ui.stream.PietContent}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.google.search.now.ui.stream.StreamStructureProto.PietContent, Builder> implements
        // @@protoc_insertion_point(builder_implements:search.now.ui.stream.PietContent)
        com.google.search.now.ui.stream.StreamStructureProto.PietContentOrBuilder {
      // Construct using com.google.search.now.ui.stream.StreamStructureProto.PietContent.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <pre>
       * Content Ids of Piet Shared States which should be provided to Piet in order
       * to show its content.
       * </pre>
       *
       * <code>repeated .search.now.proto.wire.feed.ContentId piet_shared_states = 1;</code>
       */
      public java.util.List<com.google.search.now.wire.feed.ContentIdProto.ContentId> getPietSharedStatesList() {
        return java.util.Collections.unmodifiableList(
            instance.getPietSharedStatesList());
      }
      /**
       * <pre>
       * Content Ids of Piet Shared States which should be provided to Piet in order
       * to show its content.
       * </pre>
       *
       * <code>repeated .search.now.proto.wire.feed.ContentId piet_shared_states = 1;</code>
       */
      public int getPietSharedStatesCount() {
        return instance.getPietSharedStatesCount();
      }/**
       * <pre>
       * Content Ids of Piet Shared States which should be provided to Piet in order
       * to show its content.
       * </pre>
       *
       * <code>repeated .search.now.proto.wire.feed.ContentId piet_shared_states = 1;</code>
       */
      public com.google.search.now.wire.feed.ContentIdProto.ContentId getPietSharedStates(int index) {
        return instance.getPietSharedStates(index);
      }
      /**
       * <pre>
       * Content Ids of Piet Shared States which should be provided to Piet in order
       * to show its content.
       * </pre>
       *
       * <code>repeated .search.now.proto.wire.feed.ContentId piet_shared_states = 1;</code>
       */
      public Builder setPietSharedStates(
          int index, com.google.search.now.wire.feed.ContentIdProto.ContentId value) {
        copyOnWrite();
        instance.setPietSharedStates(index, value);
        return this;
      }
      /**
       * <pre>
       * Content Ids of Piet Shared States which should be provided to Piet in order
       * to show its content.
       * </pre>
       *
       * <code>repeated .search.now.proto.wire.feed.ContentId piet_shared_states = 1;</code>
       */
      public Builder setPietSharedStates(
          int index, com.google.search.now.wire.feed.ContentIdProto.ContentId.Builder builderForValue) {
        copyOnWrite();
        instance.setPietSharedStates(index, builderForValue);
        return this;
      }
      /**
       * <pre>
       * Content Ids of Piet Shared States which should be provided to Piet in order
       * to show its content.
       * </pre>
       *
       * <code>repeated .search.now.proto.wire.feed.ContentId piet_shared_states = 1;</code>
       */
      public Builder addPietSharedStates(com.google.search.now.wire.feed.ContentIdProto.ContentId value) {
        copyOnWrite();
        instance.addPietSharedStates(value);
        return this;
      }
      /**
       * <pre>
       * Content Ids of Piet Shared States which should be provided to Piet in order
       * to show its content.
       * </pre>
       *
       * <code>repeated .search.now.proto.wire.feed.ContentId piet_shared_states = 1;</code>
       */
      public Builder addPietSharedStates(
          int index, com.google.search.now.wire.feed.ContentIdProto.ContentId value) {
        copyOnWrite();
        instance.addPietSharedStates(index, value);
        return this;
      }
      /**
       * <pre>
       * Content Ids of Piet Shared States which should be provided to Piet in order
       * to show its content.
       * </pre>
       *
       * <code>repeated .search.now.proto.wire.feed.ContentId piet_shared_states = 1;</code>
       */
      public Builder addPietSharedStates(
          com.google.search.now.wire.feed.ContentIdProto.ContentId.Builder builderForValue) {
        copyOnWrite();
        instance.addPietSharedStates(builderForValue);
        return this;
      }
      /**
       * <pre>
       * Content Ids of Piet Shared States which should be provided to Piet in order
       * to show its content.
       * </pre>
       *
       * <code>repeated .search.now.proto.wire.feed.ContentId piet_shared_states = 1;</code>
       */
      public Builder addPietSharedStates(
          int index, com.google.search.now.wire.feed.ContentIdProto.ContentId.Builder builderForValue) {
        copyOnWrite();
        instance.addPietSharedStates(index, builderForValue);
        return this;
      }
      /**
       * <pre>
       * Content Ids of Piet Shared States which should be provided to Piet in order
       * to show its content.
       * </pre>
       *
       * <code>repeated .search.now.proto.wire.feed.ContentId piet_shared_states = 1;</code>
       */
      public Builder addAllPietSharedStates(
          java.lang.Iterable<? extends com.google.search.now.wire.feed.ContentIdProto.ContentId> values) {
        copyOnWrite();
        instance.addAllPietSharedStates(values);
        return this;
      }
      /**
       * <pre>
       * Content Ids of Piet Shared States which should be provided to Piet in order
       * to show its content.
       * </pre>
       *
       * <code>repeated .search.now.proto.wire.feed.ContentId piet_shared_states = 1;</code>
       */
      public Builder clearPietSharedStates() {
        copyOnWrite();
        instance.clearPietSharedStates();
        return this;
      }
      /**
       * <pre>
       * Content Ids of Piet Shared States which should be provided to Piet in order
       * to show its content.
       * </pre>
       *
       * <code>repeated .search.now.proto.wire.feed.ContentId piet_shared_states = 1;</code>
       */
      public Builder removePietSharedStates(int index) {
        copyOnWrite();
        instance.removePietSharedStates(index);
        return this;
      }

      /**
       * <pre>
       * The Piet frame to render.
       * </pre>
       *
       * <code>optional .search.now.ui.piet.Frame frame = 2;</code>
       */
      public boolean hasFrame() {
        return instance.hasFrame();
      }
      /**
       * <pre>
       * The Piet frame to render.
       * </pre>
       *
       * <code>optional .search.now.ui.piet.Frame frame = 2;</code>
       */
      public com.google.search.now.ui.piet.PietProto.Frame getFrame() {
        return instance.getFrame();
      }
      /**
       * <pre>
       * The Piet frame to render.
       * </pre>
       *
       * <code>optional .search.now.ui.piet.Frame frame = 2;</code>
       */
      public Builder setFrame(com.google.search.now.ui.piet.PietProto.Frame value) {
        copyOnWrite();
        instance.setFrame(value);
        return this;
        }
      /**
       * <pre>
       * The Piet frame to render.
       * </pre>
       *
       * <code>optional .search.now.ui.piet.Frame frame = 2;</code>
       */
      public Builder setFrame(
          com.google.search.now.ui.piet.PietProto.Frame.Builder builderForValue) {
        copyOnWrite();
        instance.setFrame(builderForValue);
        return this;
      }
      /**
       * <pre>
       * The Piet frame to render.
       * </pre>
       *
       * <code>optional .search.now.ui.piet.Frame frame = 2;</code>
       */
      public Builder mergeFrame(com.google.search.now.ui.piet.PietProto.Frame value) {
        copyOnWrite();
        instance.mergeFrame(value);
        return this;
      }
      /**
       * <pre>
       * The Piet frame to render.
       * </pre>
       *
       * <code>optional .search.now.ui.piet.Frame frame = 2;</code>
       */
      public Builder clearFrame() {  copyOnWrite();
        instance.clearFrame();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:search.now.ui.stream.PietContent)
    }
    private byte memoizedIsInitialized = -1;
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.google.search.now.ui.stream.StreamStructureProto.PietContent();
        }
        case IS_INITIALIZED: {
          byte isInitialized = memoizedIsInitialized;
          if (isInitialized == 1) return DEFAULT_INSTANCE;
          if (isInitialized == 0) return null;

          boolean shouldMemoize = ((Boolean) arg0).booleanValue();
          if (hasFrame()) {
            if (!getFrame().isInitialized()) {
              if (shouldMemoize) {
                memoizedIsInitialized = 0;
              }
              return null;
            }
          }
          if (shouldMemoize) memoizedIsInitialized = 1;
          return DEFAULT_INSTANCE;

        }
        case MAKE_IMMUTABLE: {
          pietSharedStates_.makeImmutable();
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          com.google.search.now.ui.stream.StreamStructureProto.PietContent other = (com.google.search.now.ui.stream.StreamStructureProto.PietContent) arg1;
          pietSharedStates_= visitor.visitList(pietSharedStates_, other.pietSharedStates_);
          frame_ = visitor.visitMessage(frame_, other.frame_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
            bitField0_ |= other.bitField0_;
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!parseUnknownField(tag, input)) {
                    done = true;
                  }
                  break;
                }
                case 10: {
                  if (!pietSharedStates_.isModifiable()) {
                    pietSharedStates_ =
                        com.google.protobuf.GeneratedMessageLite.mutableCopy(pietSharedStates_);
                  }
                  pietSharedStates_.add(
                      input.readMessage(com.google.search.now.wire.feed.ContentIdProto.ContentId.parser(), extensionRegistry));
                  break;
                }
                case 18: {
                  com.google.search.now.ui.piet.PietProto.Frame.Builder subBuilder = null;
                  if (((bitField0_ & 0x00000001) == 0x00000001)) {
                    subBuilder = frame_.toBuilder();
                  }
                  frame_ = input.readMessage(com.google.search.now.ui.piet.PietProto.Frame.parser(), extensionRegistry);
                  if (subBuilder != null) {
                    subBuilder.mergeFrom(frame_);
                    frame_ = subBuilder.buildPartial();
                  }
                  bitField0_ |= 0x00000001;
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (com.google.search.now.ui.stream.StreamStructureProto.PietContent.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:search.now.ui.stream.PietContent)
    private static final com.google.search.now.ui.stream.StreamStructureProto.PietContent DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new PietContent();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static com.google.search.now.ui.stream.StreamStructureProto.PietContent getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<PietContent> PARSER;

    public static com.google.protobuf.Parser<PietContent> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
    public static final int PIET_CONTENT_EXTENSION_FIELD_NUMBER = 185431440;
    /**
     * <code>extend .search.now.ui.stream.Content { ... }</code>
     */
    public static final
      com.google.protobuf.GeneratedMessageLite.GeneratedExtension<
        com.google.search.now.ui.stream.StreamStructureProto.Content,
        com.google.search.now.ui.stream.StreamStructureProto.PietContent> pietContentExtension = com.google.protobuf.GeneratedMessageLite
            .newSingularGeneratedExtension(
          com.google.search.now.ui.stream.StreamStructureProto.Content.getDefaultInstance(),
          com.google.search.now.ui.stream.StreamStructureProto.PietContent.getDefaultInstance(),
          com.google.search.now.ui.stream.StreamStructureProto.PietContent.getDefaultInstance(),
          null,
          185431440,
          com.google.protobuf.WireFormat.FieldType.MESSAGE,
          com.google.search.now.ui.stream.StreamStructureProto.PietContent.class);
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
