// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/search/now/proto/ui/piet/accessibility.proto

package com.google.search.now.ui.piet;

public final class AccessibilityProto {
  private AccessibilityProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  /**
   * <pre>
   * Semantic roles played by a UI element related to accessibility.
   * </pre>
   *
   * Protobuf enum {@code search.now.ui.piet.AccessibilityRole}
   */
  public enum AccessibilityRole
      implements com.google.protobuf.Internal.EnumLite {
    /**
     * <pre>
     * No special role. The default value, maps to 0.
     * </pre>
     *
     * <code>ACCESSIBILITY_ROLE_UNSPECIFIED = 0;</code>
     */
    ACCESSIBILITY_ROLE_UNSPECIFIED(0),
    /**
     * <pre>
     * Indicates that the UI element is a list containing other elements.
     * </pre>
     *
     * <code>LIST = 1;</code>
     */
    LIST(1),
    /**
     * <pre>
     * Indicates that the UI element is a header for a section.
     * </pre>
     *
     * <code>HEADER = 2;</code>
     */
    HEADER(2),
    ;

    /**
     * <pre>
     * No special role. The default value, maps to 0.
     * </pre>
     *
     * <code>ACCESSIBILITY_ROLE_UNSPECIFIED = 0;</code>
     */
    public static final int ACCESSIBILITY_ROLE_UNSPECIFIED_VALUE = 0;
    /**
     * <pre>
     * Indicates that the UI element is a list containing other elements.
     * </pre>
     *
     * <code>LIST = 1;</code>
     */
    public static final int LIST_VALUE = 1;
    /**
     * <pre>
     * Indicates that the UI element is a header for a section.
     * </pre>
     *
     * <code>HEADER = 2;</code>
     */
    public static final int HEADER_VALUE = 2;


    public final int getNumber() {
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static AccessibilityRole valueOf(int value) {
      return forNumber(value);
    }

    public static AccessibilityRole forNumber(int value) {
      switch (value) {
        case 0: return ACCESSIBILITY_ROLE_UNSPECIFIED;
        case 1: return LIST;
        case 2: return HEADER;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<AccessibilityRole>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        AccessibilityRole> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<AccessibilityRole>() {
            public AccessibilityRole findValueByNumber(int number) {
              return AccessibilityRole.forNumber(number);
            }
          };

    private final int value;

    private AccessibilityRole(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:search.now.ui.piet.AccessibilityRole)
  }

  public interface AccessibilityOrBuilder extends
      // @@protoc_insertion_point(interface_extends:search.now.ui.piet.Accessibility)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <pre>
     * A string that may be spoken by the system. (TalkBack on Android, VoiceOver
     * on iOS, browser on Web)
     * </pre>
     *
     * <code>optional .search.now.ui.piet.ParameterizedText description = 1;</code>
     */
    boolean hasDescription();
    /**
     * <pre>
     * A string that may be spoken by the system. (TalkBack on Android, VoiceOver
     * on iOS, browser on Web)
     * </pre>
     *
     * <code>optional .search.now.ui.piet.ParameterizedText description = 1;</code>
     */
    com.google.search.now.ui.piet.TextProto.ParameterizedText getDescription();

    /**
     * <pre>
     * Roles that this UI element plays in the UI. These annotations will be used
     * by the accessibility framework for applying role-specific treatments.
     * </pre>
     *
     * <code>repeated .search.now.ui.piet.AccessibilityRole roles = 2;</code>
     */
    java.util.List<com.google.search.now.ui.piet.AccessibilityProto.AccessibilityRole> getRolesList();
    /**
     * <pre>
     * Roles that this UI element plays in the UI. These annotations will be used
     * by the accessibility framework for applying role-specific treatments.
     * </pre>
     *
     * <code>repeated .search.now.ui.piet.AccessibilityRole roles = 2;</code>
     */
    int getRolesCount();
    /**
     * <pre>
     * Roles that this UI element plays in the UI. These annotations will be used
     * by the accessibility framework for applying role-specific treatments.
     * </pre>
     *
     * <code>repeated .search.now.ui.piet.AccessibilityRole roles = 2;</code>
     */
    com.google.search.now.ui.piet.AccessibilityProto.AccessibilityRole getRoles(int index);
  }
  /**
   * <pre>
   * Defines accessibility related attributes for Piet elements.
   * </pre>
   *
   * Protobuf type {@code search.now.ui.piet.Accessibility}
   */
  public  static final class Accessibility extends
      com.google.protobuf.GeneratedMessageLite<
          Accessibility, Accessibility.Builder> implements
      // @@protoc_insertion_point(message_implements:search.now.ui.piet.Accessibility)
      AccessibilityOrBuilder {
    private Accessibility() {
      roles_ = emptyIntList();
    }
    private int bitField0_;
    public static final int DESCRIPTION_FIELD_NUMBER = 1;
    private com.google.search.now.ui.piet.TextProto.ParameterizedText description_;
    /**
     * <pre>
     * A string that may be spoken by the system. (TalkBack on Android, VoiceOver
     * on iOS, browser on Web)
     * </pre>
     *
     * <code>optional .search.now.ui.piet.ParameterizedText description = 1;</code>
     */
    public boolean hasDescription() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <pre>
     * A string that may be spoken by the system. (TalkBack on Android, VoiceOver
     * on iOS, browser on Web)
     * </pre>
     *
     * <code>optional .search.now.ui.piet.ParameterizedText description = 1;</code>
     */
    public com.google.search.now.ui.piet.TextProto.ParameterizedText getDescription() {
      return description_ == null ? com.google.search.now.ui.piet.TextProto.ParameterizedText.getDefaultInstance() : description_;
    }
    /**
     * <pre>
     * A string that may be spoken by the system. (TalkBack on Android, VoiceOver
     * on iOS, browser on Web)
     * </pre>
     *
     * <code>optional .search.now.ui.piet.ParameterizedText description = 1;</code>
     */
    private void setDescription(com.google.search.now.ui.piet.TextProto.ParameterizedText value) {
      if (value == null) {
        throw new NullPointerException();
      }
      description_ = value;
      bitField0_ |= 0x00000001;
      }
    /**
     * <pre>
     * A string that may be spoken by the system. (TalkBack on Android, VoiceOver
     * on iOS, browser on Web)
     * </pre>
     *
     * <code>optional .search.now.ui.piet.ParameterizedText description = 1;</code>
     */
    private void setDescription(
        com.google.search.now.ui.piet.TextProto.ParameterizedText.Builder builderForValue) {
      description_ = builderForValue.build();
      bitField0_ |= 0x00000001;
    }
    /**
     * <pre>
     * A string that may be spoken by the system. (TalkBack on Android, VoiceOver
     * on iOS, browser on Web)
     * </pre>
     *
     * <code>optional .search.now.ui.piet.ParameterizedText description = 1;</code>
     */
    private void mergeDescription(com.google.search.now.ui.piet.TextProto.ParameterizedText value) {
      if (description_ != null &&
          description_ != com.google.search.now.ui.piet.TextProto.ParameterizedText.getDefaultInstance()) {
        description_ =
          com.google.search.now.ui.piet.TextProto.ParameterizedText.newBuilder(description_).mergeFrom(value).buildPartial();
      } else {
        description_ = value;
      }
      bitField0_ |= 0x00000001;
    }
    /**
     * <pre>
     * A string that may be spoken by the system. (TalkBack on Android, VoiceOver
     * on iOS, browser on Web)
     * </pre>
     *
     * <code>optional .search.now.ui.piet.ParameterizedText description = 1;</code>
     */
    private void clearDescription() {  description_ = null;
      bitField0_ = (bitField0_ & ~0x00000001);
    }

    public static final int ROLES_FIELD_NUMBER = 2;
    private com.google.protobuf.Internal.IntList roles_;
    private static final com.google.protobuf.Internal.ListAdapter.Converter<
        java.lang.Integer, com.google.search.now.ui.piet.AccessibilityProto.AccessibilityRole> roles_converter_ =
            new com.google.protobuf.Internal.ListAdapter.Converter<
                java.lang.Integer, com.google.search.now.ui.piet.AccessibilityProto.AccessibilityRole>() {
              public com.google.search.now.ui.piet.AccessibilityProto.AccessibilityRole convert(java.lang.Integer from) {
                com.google.search.now.ui.piet.AccessibilityProto.AccessibilityRole result = com.google.search.now.ui.piet.AccessibilityProto.AccessibilityRole.forNumber(from);
                return result == null ? com.google.search.now.ui.piet.AccessibilityProto.AccessibilityRole.ACCESSIBILITY_ROLE_UNSPECIFIED : result;
              }
            };
    /**
     * <pre>
     * Roles that this UI element plays in the UI. These annotations will be used
     * by the accessibility framework for applying role-specific treatments.
     * </pre>
     *
     * <code>repeated .search.now.ui.piet.AccessibilityRole roles = 2;</code>
     */
    public java.util.List<com.google.search.now.ui.piet.AccessibilityProto.AccessibilityRole> getRolesList() {
      return new com.google.protobuf.Internal.ListAdapter<
          java.lang.Integer, com.google.search.now.ui.piet.AccessibilityProto.AccessibilityRole>(roles_, roles_converter_);
    }
    /**
     * <pre>
     * Roles that this UI element plays in the UI. These annotations will be used
     * by the accessibility framework for applying role-specific treatments.
     * </pre>
     *
     * <code>repeated .search.now.ui.piet.AccessibilityRole roles = 2;</code>
     */
    public int getRolesCount() {
      return roles_.size();
    }
    /**
     * <pre>
     * Roles that this UI element plays in the UI. These annotations will be used
     * by the accessibility framework for applying role-specific treatments.
     * </pre>
     *
     * <code>repeated .search.now.ui.piet.AccessibilityRole roles = 2;</code>
     */
    public com.google.search.now.ui.piet.AccessibilityProto.AccessibilityRole getRoles(int index) {
      return roles_converter_.convert(roles_.getInt(index));
    }
    private void ensureRolesIsMutable() {
      if (!roles_.isModifiable()) {
        roles_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(roles_);
      }
    }
    /**
     * <pre>
     * Roles that this UI element plays in the UI. These annotations will be used
     * by the accessibility framework for applying role-specific treatments.
     * </pre>
     *
     * <code>repeated .search.now.ui.piet.AccessibilityRole roles = 2;</code>
     */
    private void setRoles(
        int index, com.google.search.now.ui.piet.AccessibilityProto.AccessibilityRole value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureRolesIsMutable();
      roles_.setInt(index, value.getNumber());
    }
    /**
     * <pre>
     * Roles that this UI element plays in the UI. These annotations will be used
     * by the accessibility framework for applying role-specific treatments.
     * </pre>
     *
     * <code>repeated .search.now.ui.piet.AccessibilityRole roles = 2;</code>
     */
    private void addRoles(com.google.search.now.ui.piet.AccessibilityProto.AccessibilityRole value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureRolesIsMutable();
      roles_.addInt(value.getNumber());
    }
    /**
     * <pre>
     * Roles that this UI element plays in the UI. These annotations will be used
     * by the accessibility framework for applying role-specific treatments.
     * </pre>
     *
     * <code>repeated .search.now.ui.piet.AccessibilityRole roles = 2;</code>
     */
    private void addAllRoles(
        java.lang.Iterable<? extends com.google.search.now.ui.piet.AccessibilityProto.AccessibilityRole> values) {
      ensureRolesIsMutable();
      for (com.google.search.now.ui.piet.AccessibilityProto.AccessibilityRole value : values) {
        roles_.addInt(value.getNumber());
      }
    }
    /**
     * <pre>
     * Roles that this UI element plays in the UI. These annotations will be used
     * by the accessibility framework for applying role-specific treatments.
     * </pre>
     *
     * <code>repeated .search.now.ui.piet.AccessibilityRole roles = 2;</code>
     */
    private void clearRoles() {
      roles_ = emptyIntList();
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, getDescription());
      }
      for (int i = 0; i < roles_.size(); i++) {
        output.writeEnum(2, roles_.getInt(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getDescription());
      }
      {
        int dataSize = 0;
        for (int i = 0; i < roles_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeEnumSizeNoTag(roles_.getInt(i));
        }
        size += dataSize;
        size += 1 * roles_.size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    public static com.google.search.now.ui.piet.AccessibilityProto.Accessibility parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.google.search.now.ui.piet.AccessibilityProto.Accessibility parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.google.search.now.ui.piet.AccessibilityProto.Accessibility parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.google.search.now.ui.piet.AccessibilityProto.Accessibility parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.google.search.now.ui.piet.AccessibilityProto.Accessibility parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.google.search.now.ui.piet.AccessibilityProto.Accessibility parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.google.search.now.ui.piet.AccessibilityProto.Accessibility parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.google.search.now.ui.piet.AccessibilityProto.Accessibility parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.google.search.now.ui.piet.AccessibilityProto.Accessibility parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.google.search.now.ui.piet.AccessibilityProto.Accessibility parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.google.search.now.ui.piet.AccessibilityProto.Accessibility parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.google.search.now.ui.piet.AccessibilityProto.Accessibility parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.google.search.now.ui.piet.AccessibilityProto.Accessibility prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * <pre>
     * Defines accessibility related attributes for Piet elements.
     * </pre>
     *
     * Protobuf type {@code search.now.ui.piet.Accessibility}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.google.search.now.ui.piet.AccessibilityProto.Accessibility, Builder> implements
        // @@protoc_insertion_point(builder_implements:search.now.ui.piet.Accessibility)
        com.google.search.now.ui.piet.AccessibilityProto.AccessibilityOrBuilder {
      // Construct using com.google.search.now.ui.piet.AccessibilityProto.Accessibility.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <pre>
       * A string that may be spoken by the system. (TalkBack on Android, VoiceOver
       * on iOS, browser on Web)
       * </pre>
       *
       * <code>optional .search.now.ui.piet.ParameterizedText description = 1;</code>
       */
      public boolean hasDescription() {
        return instance.hasDescription();
      }
      /**
       * <pre>
       * A string that may be spoken by the system. (TalkBack on Android, VoiceOver
       * on iOS, browser on Web)
       * </pre>
       *
       * <code>optional .search.now.ui.piet.ParameterizedText description = 1;</code>
       */
      public com.google.search.now.ui.piet.TextProto.ParameterizedText getDescription() {
        return instance.getDescription();
      }
      /**
       * <pre>
       * A string that may be spoken by the system. (TalkBack on Android, VoiceOver
       * on iOS, browser on Web)
       * </pre>
       *
       * <code>optional .search.now.ui.piet.ParameterizedText description = 1;</code>
       */
      public Builder setDescription(com.google.search.now.ui.piet.TextProto.ParameterizedText value) {
        copyOnWrite();
        instance.setDescription(value);
        return this;
        }
      /**
       * <pre>
       * A string that may be spoken by the system. (TalkBack on Android, VoiceOver
       * on iOS, browser on Web)
       * </pre>
       *
       * <code>optional .search.now.ui.piet.ParameterizedText description = 1;</code>
       */
      public Builder setDescription(
          com.google.search.now.ui.piet.TextProto.ParameterizedText.Builder builderForValue) {
        copyOnWrite();
        instance.setDescription(builderForValue);
        return this;
      }
      /**
       * <pre>
       * A string that may be spoken by the system. (TalkBack on Android, VoiceOver
       * on iOS, browser on Web)
       * </pre>
       *
       * <code>optional .search.now.ui.piet.ParameterizedText description = 1;</code>
       */
      public Builder mergeDescription(com.google.search.now.ui.piet.TextProto.ParameterizedText value) {
        copyOnWrite();
        instance.mergeDescription(value);
        return this;
      }
      /**
       * <pre>
       * A string that may be spoken by the system. (TalkBack on Android, VoiceOver
       * on iOS, browser on Web)
       * </pre>
       *
       * <code>optional .search.now.ui.piet.ParameterizedText description = 1;</code>
       */
      public Builder clearDescription() {  copyOnWrite();
        instance.clearDescription();
        return this;
      }

      /**
       * <pre>
       * Roles that this UI element plays in the UI. These annotations will be used
       * by the accessibility framework for applying role-specific treatments.
       * </pre>
       *
       * <code>repeated .search.now.ui.piet.AccessibilityRole roles = 2;</code>
       */
      public java.util.List<com.google.search.now.ui.piet.AccessibilityProto.AccessibilityRole> getRolesList() {
        return instance.getRolesList();
      }
      /**
       * <pre>
       * Roles that this UI element plays in the UI. These annotations will be used
       * by the accessibility framework for applying role-specific treatments.
       * </pre>
       *
       * <code>repeated .search.now.ui.piet.AccessibilityRole roles = 2;</code>
       */
      public int getRolesCount() {
        return instance.getRolesCount();
      }
      /**
       * <pre>
       * Roles that this UI element plays in the UI. These annotations will be used
       * by the accessibility framework for applying role-specific treatments.
       * </pre>
       *
       * <code>repeated .search.now.ui.piet.AccessibilityRole roles = 2;</code>
       */
      public com.google.search.now.ui.piet.AccessibilityProto.AccessibilityRole getRoles(int index) {
        return instance.getRoles(index);
      }
      /**
       * <pre>
       * Roles that this UI element plays in the UI. These annotations will be used
       * by the accessibility framework for applying role-specific treatments.
       * </pre>
       *
       * <code>repeated .search.now.ui.piet.AccessibilityRole roles = 2;</code>
       */
      public Builder setRoles(
          int index, com.google.search.now.ui.piet.AccessibilityProto.AccessibilityRole value) {
        copyOnWrite();
        instance.setRoles(index, value);
        return this;
      }
      /**
       * <pre>
       * Roles that this UI element plays in the UI. These annotations will be used
       * by the accessibility framework for applying role-specific treatments.
       * </pre>
       *
       * <code>repeated .search.now.ui.piet.AccessibilityRole roles = 2;</code>
       */
      public Builder addRoles(com.google.search.now.ui.piet.AccessibilityProto.AccessibilityRole value) {
        copyOnWrite();
        instance.addRoles(value);
        return this;
      }
      /**
       * <pre>
       * Roles that this UI element plays in the UI. These annotations will be used
       * by the accessibility framework for applying role-specific treatments.
       * </pre>
       *
       * <code>repeated .search.now.ui.piet.AccessibilityRole roles = 2;</code>
       */
      public Builder addAllRoles(
          java.lang.Iterable<? extends com.google.search.now.ui.piet.AccessibilityProto.AccessibilityRole> values) {
        copyOnWrite();
        instance.addAllRoles(values);  return this;
      }
      /**
       * <pre>
       * Roles that this UI element plays in the UI. These annotations will be used
       * by the accessibility framework for applying role-specific treatments.
       * </pre>
       *
       * <code>repeated .search.now.ui.piet.AccessibilityRole roles = 2;</code>
       */
      public Builder clearRoles() {
        copyOnWrite();
        instance.clearRoles();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:search.now.ui.piet.Accessibility)
    }
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.google.search.now.ui.piet.AccessibilityProto.Accessibility();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          roles_.makeImmutable();
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          com.google.search.now.ui.piet.AccessibilityProto.Accessibility other = (com.google.search.now.ui.piet.AccessibilityProto.Accessibility) arg1;
          description_ = visitor.visitMessage(description_, other.description_);
          roles_= visitor.visitIntList(roles_, other.roles_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
            bitField0_ |= other.bitField0_;
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!parseUnknownField(tag, input)) {
                    done = true;
                  }
                  break;
                }
                case 10: {
                  com.google.search.now.ui.piet.TextProto.ParameterizedText.Builder subBuilder = null;
                  if (((bitField0_ & 0x00000001) == 0x00000001)) {
                    subBuilder = description_.toBuilder();
                  }
                  description_ = input.readMessage(com.google.search.now.ui.piet.TextProto.ParameterizedText.parser(), extensionRegistry);
                  if (subBuilder != null) {
                    subBuilder.mergeFrom(description_);
                    description_ = subBuilder.buildPartial();
                  }
                  bitField0_ |= 0x00000001;
                  break;
                }
                case 16: {
                  if (!roles_.isModifiable()) {
                    roles_ =
                        com.google.protobuf.GeneratedMessageLite.mutableCopy(roles_);
                  }
                  int rawValue = input.readEnum();
                  com.google.search.now.ui.piet.AccessibilityProto.AccessibilityRole value = com.google.search.now.ui.piet.AccessibilityProto.AccessibilityRole.forNumber(rawValue);
                  if (value == null) {
                    super.mergeVarintField(2, rawValue);
                  } else {
                    roles_.addInt(rawValue);
                  }
                  break;
                }
                case 18: {
                  if (!roles_.isModifiable()) {
                    roles_ =
                        com.google.protobuf.GeneratedMessageLite.mutableCopy(roles_);
                  }
                  int length = input.readRawVarint32();
                  int oldLimit = input.pushLimit(length);
                  while(input.getBytesUntilLimit() > 0) {
                    int rawValue = input.readEnum();
                    com.google.search.now.ui.piet.AccessibilityProto.AccessibilityRole value = com.google.search.now.ui.piet.AccessibilityProto.AccessibilityRole.forNumber(rawValue);
                    if (value == null) {
                      super.mergeVarintField(2, rawValue);
                    } else {
                      roles_.addInt(rawValue);
                    }
                  }
                  input.popLimit(oldLimit);
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (com.google.search.now.ui.piet.AccessibilityProto.Accessibility.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:search.now.ui.piet.Accessibility)
    private static final com.google.search.now.ui.piet.AccessibilityProto.Accessibility DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Accessibility();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static com.google.search.now.ui.piet.AccessibilityProto.Accessibility getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<Accessibility> PARSER;

    public static com.google.protobuf.Parser<Accessibility> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
