// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/search/now/proto/wire/feed/feed_response.proto

package com.google.search.now.wire.feed;

public final class FeedResponseProto {
  private FeedResponseProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
    registry.add(com.google.search.now.wire.feed.FeedResponseProto.FeedResponse.feedResponse);
  }
  public interface FeedResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:search.now.proto.wire.feed.FeedResponse)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <pre>
     * DataOperations are applied on the client in order in which they are
     * received.
     * </pre>
     *
     * <code>repeated .search.now.proto.wire.feed.DataOperation data_operation = 1;</code>
     */
    java.util.List<com.google.search.now.wire.feed.DataOperationProto.DataOperation> 
        getDataOperationList();
    /**
     * <pre>
     * DataOperations are applied on the client in order in which they are
     * received.
     * </pre>
     *
     * <code>repeated .search.now.proto.wire.feed.DataOperation data_operation = 1;</code>
     */
    com.google.search.now.wire.feed.DataOperationProto.DataOperation getDataOperation(int index);
    /**
     * <pre>
     * DataOperations are applied on the client in order in which they are
     * received.
     * </pre>
     *
     * <code>repeated .search.now.proto.wire.feed.DataOperation data_operation = 1;</code>
     */
    int getDataOperationCount();
  }
  /**
   * <pre>
   * A feed response is  a series of directives to manipulate backend storage,
   * similar to database commands.  Individual data operations contain all the
   * necessary information to manipulate the client state.
   * </pre>
   *
   * Protobuf type {@code search.now.proto.wire.feed.FeedResponse}
   */
  public  static final class FeedResponse extends
      com.google.protobuf.GeneratedMessageLite<
          FeedResponse, FeedResponse.Builder> implements
      // @@protoc_insertion_point(message_implements:search.now.proto.wire.feed.FeedResponse)
      FeedResponseOrBuilder {
    private FeedResponse() {
      dataOperation_ = emptyProtobufList();
    }
    public static final int DATA_OPERATION_FIELD_NUMBER = 1;
    private com.google.protobuf.Internal.ProtobufList<com.google.search.now.wire.feed.DataOperationProto.DataOperation> dataOperation_;
    /**
     * <pre>
     * DataOperations are applied on the client in order in which they are
     * received.
     * </pre>
     *
     * <code>repeated .search.now.proto.wire.feed.DataOperation data_operation = 1;</code>
     */
    public java.util.List<com.google.search.now.wire.feed.DataOperationProto.DataOperation> getDataOperationList() {
      return dataOperation_;
    }
    /**
     * <pre>
     * DataOperations are applied on the client in order in which they are
     * received.
     * </pre>
     *
     * <code>repeated .search.now.proto.wire.feed.DataOperation data_operation = 1;</code>
     */
    public java.util.List<? extends com.google.search.now.wire.feed.DataOperationProto.DataOperationOrBuilder> 
        getDataOperationOrBuilderList() {
      return dataOperation_;
    }
    /**
     * <pre>
     * DataOperations are applied on the client in order in which they are
     * received.
     * </pre>
     *
     * <code>repeated .search.now.proto.wire.feed.DataOperation data_operation = 1;</code>
     */
    public int getDataOperationCount() {
      return dataOperation_.size();
    }
    /**
     * <pre>
     * DataOperations are applied on the client in order in which they are
     * received.
     * </pre>
     *
     * <code>repeated .search.now.proto.wire.feed.DataOperation data_operation = 1;</code>
     */
    public com.google.search.now.wire.feed.DataOperationProto.DataOperation getDataOperation(int index) {
      return dataOperation_.get(index);
    }
    /**
     * <pre>
     * DataOperations are applied on the client in order in which they are
     * received.
     * </pre>
     *
     * <code>repeated .search.now.proto.wire.feed.DataOperation data_operation = 1;</code>
     */
    public com.google.search.now.wire.feed.DataOperationProto.DataOperationOrBuilder getDataOperationOrBuilder(
        int index) {
      return dataOperation_.get(index);
    }
    private void ensureDataOperationIsMutable() {
      if (!dataOperation_.isModifiable()) {
        dataOperation_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(dataOperation_);
       }
    }

    /**
     * <pre>
     * DataOperations are applied on the client in order in which they are
     * received.
     * </pre>
     *
     * <code>repeated .search.now.proto.wire.feed.DataOperation data_operation = 1;</code>
     */
    private void setDataOperation(
        int index, com.google.search.now.wire.feed.DataOperationProto.DataOperation value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureDataOperationIsMutable();
      dataOperation_.set(index, value);
    }
    /**
     * <pre>
     * DataOperations are applied on the client in order in which they are
     * received.
     * </pre>
     *
     * <code>repeated .search.now.proto.wire.feed.DataOperation data_operation = 1;</code>
     */
    private void setDataOperation(
        int index, com.google.search.now.wire.feed.DataOperationProto.DataOperation.Builder builderForValue) {
      ensureDataOperationIsMutable();
      dataOperation_.set(index, builderForValue.build());
    }
    /**
     * <pre>
     * DataOperations are applied on the client in order in which they are
     * received.
     * </pre>
     *
     * <code>repeated .search.now.proto.wire.feed.DataOperation data_operation = 1;</code>
     */
    private void addDataOperation(com.google.search.now.wire.feed.DataOperationProto.DataOperation value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureDataOperationIsMutable();
      dataOperation_.add(value);
    }
    /**
     * <pre>
     * DataOperations are applied on the client in order in which they are
     * received.
     * </pre>
     *
     * <code>repeated .search.now.proto.wire.feed.DataOperation data_operation = 1;</code>
     */
    private void addDataOperation(
        int index, com.google.search.now.wire.feed.DataOperationProto.DataOperation value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureDataOperationIsMutable();
      dataOperation_.add(index, value);
    }
    /**
     * <pre>
     * DataOperations are applied on the client in order in which they are
     * received.
     * </pre>
     *
     * <code>repeated .search.now.proto.wire.feed.DataOperation data_operation = 1;</code>
     */
    private void addDataOperation(
        com.google.search.now.wire.feed.DataOperationProto.DataOperation.Builder builderForValue) {
      ensureDataOperationIsMutable();
      dataOperation_.add(builderForValue.build());
    }
    /**
     * <pre>
     * DataOperations are applied on the client in order in which they are
     * received.
     * </pre>
     *
     * <code>repeated .search.now.proto.wire.feed.DataOperation data_operation = 1;</code>
     */
    private void addDataOperation(
        int index, com.google.search.now.wire.feed.DataOperationProto.DataOperation.Builder builderForValue) {
      ensureDataOperationIsMutable();
      dataOperation_.add(index, builderForValue.build());
    }
    /**
     * <pre>
     * DataOperations are applied on the client in order in which they are
     * received.
     * </pre>
     *
     * <code>repeated .search.now.proto.wire.feed.DataOperation data_operation = 1;</code>
     */
    private void addAllDataOperation(
        java.lang.Iterable<? extends com.google.search.now.wire.feed.DataOperationProto.DataOperation> values) {
      ensureDataOperationIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, dataOperation_);
    }
    /**
     * <pre>
     * DataOperations are applied on the client in order in which they are
     * received.
     * </pre>
     *
     * <code>repeated .search.now.proto.wire.feed.DataOperation data_operation = 1;</code>
     */
    private void clearDataOperation() {
      dataOperation_ = emptyProtobufList();
    }
    /**
     * <pre>
     * DataOperations are applied on the client in order in which they are
     * received.
     * </pre>
     *
     * <code>repeated .search.now.proto.wire.feed.DataOperation data_operation = 1;</code>
     */
    private void removeDataOperation(int index) {
      ensureDataOperationIsMutable();
      dataOperation_.remove(index);
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < dataOperation_.size(); i++) {
        output.writeMessage(1, dataOperation_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < dataOperation_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, dataOperation_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    public static com.google.search.now.wire.feed.FeedResponseProto.FeedResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.google.search.now.wire.feed.FeedResponseProto.FeedResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.google.search.now.wire.feed.FeedResponseProto.FeedResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.google.search.now.wire.feed.FeedResponseProto.FeedResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.google.search.now.wire.feed.FeedResponseProto.FeedResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.google.search.now.wire.feed.FeedResponseProto.FeedResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.google.search.now.wire.feed.FeedResponseProto.FeedResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.google.search.now.wire.feed.FeedResponseProto.FeedResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.google.search.now.wire.feed.FeedResponseProto.FeedResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.google.search.now.wire.feed.FeedResponseProto.FeedResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.google.search.now.wire.feed.FeedResponseProto.FeedResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.google.search.now.wire.feed.FeedResponseProto.FeedResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.google.search.now.wire.feed.FeedResponseProto.FeedResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * <pre>
     * A feed response is  a series of directives to manipulate backend storage,
     * similar to database commands.  Individual data operations contain all the
     * necessary information to manipulate the client state.
     * </pre>
     *
     * Protobuf type {@code search.now.proto.wire.feed.FeedResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.google.search.now.wire.feed.FeedResponseProto.FeedResponse, Builder> implements
        // @@protoc_insertion_point(builder_implements:search.now.proto.wire.feed.FeedResponse)
        com.google.search.now.wire.feed.FeedResponseProto.FeedResponseOrBuilder {
      // Construct using com.google.search.now.wire.feed.FeedResponseProto.FeedResponse.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <pre>
       * DataOperations are applied on the client in order in which they are
       * received.
       * </pre>
       *
       * <code>repeated .search.now.proto.wire.feed.DataOperation data_operation = 1;</code>
       */
      public java.util.List<com.google.search.now.wire.feed.DataOperationProto.DataOperation> getDataOperationList() {
        return java.util.Collections.unmodifiableList(
            instance.getDataOperationList());
      }
      /**
       * <pre>
       * DataOperations are applied on the client in order in which they are
       * received.
       * </pre>
       *
       * <code>repeated .search.now.proto.wire.feed.DataOperation data_operation = 1;</code>
       */
      public int getDataOperationCount() {
        return instance.getDataOperationCount();
      }/**
       * <pre>
       * DataOperations are applied on the client in order in which they are
       * received.
       * </pre>
       *
       * <code>repeated .search.now.proto.wire.feed.DataOperation data_operation = 1;</code>
       */
      public com.google.search.now.wire.feed.DataOperationProto.DataOperation getDataOperation(int index) {
        return instance.getDataOperation(index);
      }
      /**
       * <pre>
       * DataOperations are applied on the client in order in which they are
       * received.
       * </pre>
       *
       * <code>repeated .search.now.proto.wire.feed.DataOperation data_operation = 1;</code>
       */
      public Builder setDataOperation(
          int index, com.google.search.now.wire.feed.DataOperationProto.DataOperation value) {
        copyOnWrite();
        instance.setDataOperation(index, value);
        return this;
      }
      /**
       * <pre>
       * DataOperations are applied on the client in order in which they are
       * received.
       * </pre>
       *
       * <code>repeated .search.now.proto.wire.feed.DataOperation data_operation = 1;</code>
       */
      public Builder setDataOperation(
          int index, com.google.search.now.wire.feed.DataOperationProto.DataOperation.Builder builderForValue) {
        copyOnWrite();
        instance.setDataOperation(index, builderForValue);
        return this;
      }
      /**
       * <pre>
       * DataOperations are applied on the client in order in which they are
       * received.
       * </pre>
       *
       * <code>repeated .search.now.proto.wire.feed.DataOperation data_operation = 1;</code>
       */
      public Builder addDataOperation(com.google.search.now.wire.feed.DataOperationProto.DataOperation value) {
        copyOnWrite();
        instance.addDataOperation(value);
        return this;
      }
      /**
       * <pre>
       * DataOperations are applied on the client in order in which they are
       * received.
       * </pre>
       *
       * <code>repeated .search.now.proto.wire.feed.DataOperation data_operation = 1;</code>
       */
      public Builder addDataOperation(
          int index, com.google.search.now.wire.feed.DataOperationProto.DataOperation value) {
        copyOnWrite();
        instance.addDataOperation(index, value);
        return this;
      }
      /**
       * <pre>
       * DataOperations are applied on the client in order in which they are
       * received.
       * </pre>
       *
       * <code>repeated .search.now.proto.wire.feed.DataOperation data_operation = 1;</code>
       */
      public Builder addDataOperation(
          com.google.search.now.wire.feed.DataOperationProto.DataOperation.Builder builderForValue) {
        copyOnWrite();
        instance.addDataOperation(builderForValue);
        return this;
      }
      /**
       * <pre>
       * DataOperations are applied on the client in order in which they are
       * received.
       * </pre>
       *
       * <code>repeated .search.now.proto.wire.feed.DataOperation data_operation = 1;</code>
       */
      public Builder addDataOperation(
          int index, com.google.search.now.wire.feed.DataOperationProto.DataOperation.Builder builderForValue) {
        copyOnWrite();
        instance.addDataOperation(index, builderForValue);
        return this;
      }
      /**
       * <pre>
       * DataOperations are applied on the client in order in which they are
       * received.
       * </pre>
       *
       * <code>repeated .search.now.proto.wire.feed.DataOperation data_operation = 1;</code>
       */
      public Builder addAllDataOperation(
          java.lang.Iterable<? extends com.google.search.now.wire.feed.DataOperationProto.DataOperation> values) {
        copyOnWrite();
        instance.addAllDataOperation(values);
        return this;
      }
      /**
       * <pre>
       * DataOperations are applied on the client in order in which they are
       * received.
       * </pre>
       *
       * <code>repeated .search.now.proto.wire.feed.DataOperation data_operation = 1;</code>
       */
      public Builder clearDataOperation() {
        copyOnWrite();
        instance.clearDataOperation();
        return this;
      }
      /**
       * <pre>
       * DataOperations are applied on the client in order in which they are
       * received.
       * </pre>
       *
       * <code>repeated .search.now.proto.wire.feed.DataOperation data_operation = 1;</code>
       */
      public Builder removeDataOperation(int index) {
        copyOnWrite();
        instance.removeDataOperation(index);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:search.now.proto.wire.feed.FeedResponse)
    }
    private byte memoizedIsInitialized = -1;
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.google.search.now.wire.feed.FeedResponseProto.FeedResponse();
        }
        case IS_INITIALIZED: {
          byte isInitialized = memoizedIsInitialized;
          if (isInitialized == 1) return DEFAULT_INSTANCE;
          if (isInitialized == 0) return null;

          boolean shouldMemoize = ((Boolean) arg0).booleanValue();
          for (int i = 0; i < getDataOperationCount(); i++) {
            if (!getDataOperation(i).isInitialized()) {
              if (shouldMemoize) {
                memoizedIsInitialized = 0;
              }
              return null;
            }
          }
          if (shouldMemoize) memoizedIsInitialized = 1;
          return DEFAULT_INSTANCE;

        }
        case MAKE_IMMUTABLE: {
          dataOperation_.makeImmutable();
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          com.google.search.now.wire.feed.FeedResponseProto.FeedResponse other = (com.google.search.now.wire.feed.FeedResponseProto.FeedResponse) arg1;
          dataOperation_= visitor.visitList(dataOperation_, other.dataOperation_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!parseUnknownField(tag, input)) {
                    done = true;
                  }
                  break;
                }
                case 10: {
                  if (!dataOperation_.isModifiable()) {
                    dataOperation_ =
                        com.google.protobuf.GeneratedMessageLite.mutableCopy(dataOperation_);
                  }
                  dataOperation_.add(
                      input.readMessage(com.google.search.now.wire.feed.DataOperationProto.DataOperation.parser(), extensionRegistry));
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (com.google.search.now.wire.feed.FeedResponseProto.FeedResponse.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:search.now.proto.wire.feed.FeedResponse)
    private static final com.google.search.now.wire.feed.FeedResponseProto.FeedResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new FeedResponse();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static com.google.search.now.wire.feed.FeedResponseProto.FeedResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<FeedResponse> PARSER;

    public static com.google.protobuf.Parser<FeedResponse> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
    public static final int FEED_RESPONSE_FIELD_NUMBER = 1000;
    /**
     * <code>extend .search.now.proto.wire.feed.Response { ... }</code>
     */
    public static final
      com.google.protobuf.GeneratedMessageLite.GeneratedExtension<
        com.google.search.now.wire.feed.ResponseProto.Response,
        com.google.search.now.wire.feed.FeedResponseProto.FeedResponse> feedResponse = com.google.protobuf.GeneratedMessageLite
            .newSingularGeneratedExtension(
          com.google.search.now.wire.feed.ResponseProto.Response.getDefaultInstance(),
          com.google.search.now.wire.feed.FeedResponseProto.FeedResponse.getDefaultInstance(),
          com.google.search.now.wire.feed.FeedResponseProto.FeedResponse.getDefaultInstance(),
          null,
          1000,
          com.google.protobuf.WireFormat.FieldType.MESSAGE,
          com.google.search.now.wire.feed.FeedResponseProto.FeedResponse.class);
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
